#!/usr/bin/env python3
"""Refresh star counts for every bundled submodule and write STARS.md.

Reads .gitmodules, queries the GitHub API for each repo's current star count,
and writes a sorted STARS.md leaderboard. Uses $GITHUB_TOKEN if present to lift
the rate limit. Safe to run locally or in CI.
"""
from __future__ import annotations

import configparser
import datetime as dt
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GITMODULES = ROOT / ".gitmodules"
OUT = ROOT / "STARS.md"
API = "https://api.github.com/repos/"


def parse_submodules() -> list[tuple[str, str]]:
    """Return (path, owner/repo) for each submodule."""
    cfg = configparser.ConfigParser()
    cfg.read(GITMODULES)
    out = []
    for section in cfg.sections():
        path = cfg[section].get("path", "")
        url = cfg[section].get("url", "").rstrip("/")
        if url.endswith(".git"):
            url = url[:-4]
        slug = "/".join(url.split("/")[-2:])
        if path and slug:
            out.append((path, slug))
    return out


def get_stars(slug: str) -> int | None:
    req = urllib.request.Request(API + slug)
    req.add_header("Accept", "application/vnd.github+json")
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.load(r).get("stargazers_count")
    except urllib.error.HTTPError as e:
        print(f"  ! {slug}: HTTP {e.code}", file=sys.stderr)
    except Exception as e:  # noqa: BLE001
        print(f"  ! {slug}: {e}", file=sys.stderr)
    return None


def fmt(n: int) -> str:
    return f"{n/1000:.1f}k" if n >= 1000 else str(n)


def main() -> int:
    subs = parse_submodules()
    rows = []
    for path, slug in subs:
        stars = get_stars(slug)
        print(f"  {slug}: {stars}")
        rows.append((stars if stars is not None else -1, path, slug))
    rows.sort(reverse=True)

    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# ⭐ Star Leaderboard",
        "",
        f"Auto-generated by [`scripts/update-stars.py`](scripts/update-stars.py). "
        f"Last refreshed: **{now}**.",
        "",
        f"Total bundled repos: **{len(rows)}**",
        "",
        "| # | ⭐ | Repo | Bundled at |",
        "|---|---|---|---|",
    ]
    for i, (stars, path, slug) in enumerate(rows, 1):
        s = fmt(stars) if stars >= 0 else "n/a"
        lines.append(f"| {i} | {s} | [{slug}](https://github.com/{slug}) | `{path}` |")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(rows)} repos).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
