#!/usr/bin/env python3
"""Build a markdown safety scan summary for vendored skill collections."""
from __future__ import annotations

import argparse
import importlib.util
import sys
from collections import Counter
from pathlib import Path
from types import ModuleType

ROOT = Path(__file__).resolve().parent.parent
REPORT_PATH = ROOT / "catalog" / "SAFETY.md"
SCAN_PATH = ROOT / "scripts" / "scan-skill-safety.py"


def load_scan_module() -> ModuleType:
    spec = importlib.util.spec_from_file_location("scan_skill_safety_report_module", SCAN_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {SCAN_PATH.relative_to(ROOT)}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


scan = load_scan_module()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "roots",
        nargs="*",
        default=["skills"],
        help="Directories to scan, relative to repo root unless absolute.",
    )
    parser.add_argument(
        "--min-severity",
        choices=scan.SEVERITY,
        default="high",
        help="Only include findings at this severity or above.",
    )
    parser.add_argument(
        "--max-bytes",
        type=int,
        default=750_000,
        help="Skip individual files larger than this many bytes.",
    )
    parser.add_argument(
        "--max-examples",
        type=int,
        default=40,
        help="Maximum example findings to include in the report.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify catalog/SAFETY.md is current without writing it",
    )
    return parser.parse_args()


def collect_findings(roots: list[str], min_severity: str, max_bytes: int) -> list:
    resolved = [scan.resolve_root(value) for value in roots]
    missing = scan.missing_roots(resolved)
    if missing:
        missing_list = ", ".join(missing)
        raise FileNotFoundError(f"scan root does not exist: {missing_list}")
    findings = []
    for path in scan.iter_files(resolved, max_bytes):
        findings.extend(scan.scan_file(path, min_severity))
    findings.sort(key=scan.sort_key)
    return findings


def collection_from_path(path: str) -> str:
    parts = Path(path).parts
    if len(parts) >= 2 and parts[0] == "skills":
        return parts[1]
    return "(outside skills)"


def md_escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_count_table(headers: tuple[str, str], counts: Counter[str], limit: int = 20) -> list[str]:
    lines = [f"| {headers[0]} | {headers[1]} |", "|---|---:|"]
    for label, count in counts.most_common(limit):
        lines.append(f"| `{md_escape(label)}` | {count} |")
    if len(counts) > limit:
        lines.append(f"| _Other_ | {sum(counts.values()) - sum(count for _, count in counts.most_common(limit))} |")
    return lines


def render_report(
    findings: list,
    roots: list[str],
    min_severity: str,
    max_examples: int,
) -> str:
    by_severity = Counter(finding.severity for finding in findings)
    by_rule = Counter(finding.rule_id for finding in findings)
    by_collection = Counter(collection_from_path(finding.path) for finding in findings)

    lines = [
        "# Skill Safety Scan",
        "",
        "This report is generated by `tools/build_safety_report.py` from the heuristic rules in `scripts/scan-skill-safety.py`.",
        "It is reviewer-assist output, not a proof that a skill is safe or unsafe.",
        "",
        f"- Scope: `{', '.join(roots)}`",
        f"- Minimum severity: `{min_severity}`",
        f"- Findings: **{len(findings)}**",
        f"- Critical: **{by_severity.get('critical', 0)}**",
        f"- High: **{by_severity.get('high', 0)}**",
        "",
        "## By Rule",
        "",
        *render_count_table(("Rule", "Findings"), by_rule),
        "",
        "## Top Collections",
        "",
        *render_count_table(("Collection", "Findings"), by_collection),
        "",
        "## Example Findings",
        "",
    ]

    if findings:
        lines.extend([
            "| Severity | Rule | Location | Match |",
            "|---|---|---|---|",
        ])
        shown = findings if max_examples <= 0 else findings[:max_examples]
        for finding in shown:
            location = f"{finding.path}:{finding.line}"
            lines.append(
                f"| {finding.severity} | `{md_escape(finding.rule_id)}` | "
                f"`{md_escape(location)}` | `{md_escape(finding.match)}` |"
            )
        if max_examples > 0 and len(findings) > max_examples:
            lines.append("")
            lines.append(f"_Truncated {len(findings) - max_examples} additional findings._")
    else:
        lines.append("No findings at the selected severity threshold.")

    lines.extend([
        "",
        "## Regenerate",
        "",
        "```bash",
        "make safety-report",
        "python3 scripts/scan-skill-safety.py skills --max-findings 20 --fail-on none",
        "```",
    ])
    return "\n".join(lines) + "\n"


def write_report(report: str) -> None:
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")


def check_report(report: str) -> int:
    if not REPORT_PATH.exists():
        print("ERROR: missing catalog/SAFETY.md")
        print("Run: python3 tools/build_safety_report.py")
        return 1
    if REPORT_PATH.read_text(encoding="utf-8") != report:
        print("ERROR: catalog/SAFETY.md is outdated")
        print("Run: python3 tools/build_safety_report.py")
        return 1
    print("OK: catalog/SAFETY.md is current")
    return 0


def main() -> int:
    args = parse_args()
    try:
        findings = collect_findings(args.roots, args.min_severity, args.max_bytes)
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    report = render_report(findings, args.roots, args.min_severity, args.max_examples)

    print(
        f"Scanned {', '.join(args.roots)}: {len(findings)} findings "
        f"at {args.min_severity}+ severity."
    )
    if args.check:
        return check_report(report)

    write_report(report)
    print(f"  wrote {REPORT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
