#!/usr/bin/env python3
"""Build catalog/FRONTMATTER.md: a SKILL.md frontmatter conformance report.

Most agent runtimes trigger a skill from its YAML frontmatter (`name` +
`description`). A skill that hides its frontmatter behind a watermark banner,
omits `name`, or ships no frontmatter at all will silently fail to trigger. The
two exemplar collections this hub studied (`nature-skills`,
`academic-research-skills`) both have *inconsistent* frontmatter across their
own skills — some carry `version`/`author`, most don't — with no schema to
enforce it (see `docs/skill-design-patterns.md` §7).

This tool defines a **minimal, deliberately lax schema** and measures how many
vendored skills conform, per collection. It does not edit anything (submodules
are vendored read-only) — it reports, so a maintainer can weight conformance
when curating and file upstream fixes.

Schema
------
- REQUIRED    : `name`, `description` (both present and non-empty)
- RECOMMENDED : `license`, `version` (coverage reported, never required)

A skill *conforms* when it has real YAML frontmatter carrying a non-empty
`name` and `description`. Everything else is advisory.

The report is timestamp-free so ``--check`` can compare it byte-for-byte
against a fresh regeneration (same discipline as the other catalog tools).

    python3 tools/check_frontmatter.py           # write catalog/FRONTMATTER.md
    python3 tools/check_frontmatter.py --check    # verify it is current
"""
from __future__ import annotations

import argparse
import collections
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

# Reuse the exact frontmatter parser + skill walker the catalog uses, so this
# report agrees with catalog/skills.json on what "has frontmatter" means.
from tools.build_catalog import (  # noqa: E402
    clean_description,
    collection_of,
    iter_skill_files,
    load_submodule_urls,
    parse_frontmatter,
)

REPORT_PATH = ROOT / "catalog" / "FRONTMATTER.md"

REQUIRED_FIELDS = ("name", "description")
RECOMMENDED_FIELDS = ("license", "version")


@dataclass
class SkillFM:
    path: str
    collection: str
    has_frontmatter: bool
    has_name: bool
    has_description: bool
    has_license: bool
    has_version: bool

    @property
    def conforms(self) -> bool:
        return self.has_frontmatter and self.has_name and self.has_description


def scan() -> list[SkillFM]:
    """Walk every SKILL.md and record which schema fields it carries."""
    rows: list[SkillFM] = []
    for skill_md in iter_skill_files():
        try:
            text = skill_md.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        meta, _body, has_fm = parse_frontmatter(text)
        collection, _depth = collection_of(skill_md)
        rows.append(
            SkillFM(
                path=str(skill_md.relative_to(ROOT)),
                collection=collection,
                has_frontmatter=has_fm,
                has_name=bool(meta.get("name", "").strip()),
                has_description=bool(clean_description(meta.get("description", ""))),
                has_license=bool(meta.get("license", "").strip()),
                has_version=bool(meta.get("version", "").strip()),
            )
        )
    return rows


def md_escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def pct(part: int, whole: int) -> int:
    return round(100 * part / whole) if whole else 0


def render_report(rows: list[SkillFM], offender_rows: int = 15) -> str:
    total = len(rows)
    conforming = sum(1 for r in rows if r.conforms)
    no_fm = sum(1 for r in rows if not r.has_frontmatter)
    no_name = sum(1 for r in rows if r.has_frontmatter and not r.has_name)
    no_desc = sum(1 for r in rows if r.has_frontmatter and not r.has_description)
    with_license = sum(1 for r in rows if r.has_license)
    with_version = sum(1 for r in rows if r.has_version)

    # Per-collection non-conformance (skills that will not trigger by
    # name/description in a strict loader).
    by_collection_total: collections.Counter = collections.Counter()
    by_collection_bad: collections.Counter = collections.Counter()
    for r in rows:
        by_collection_total[r.collection] += 1
        if not r.conforms:
            by_collection_bad[r.collection] += 1
    offenders = sorted(
        ((name, count) for name, count in by_collection_bad.items() if count),
        key=lambda kv: (-kv[1], kv[0]),
    )

    lines: list[str] = [
        "# 🧾 Frontmatter conformance",
        "",
        "Generated by `tools/check_frontmatter.py` by parsing every vendored",
        "`SKILL.md` with the same frontmatter parser the catalog uses. These are",
        "**findings for the maintainer**, not edits — submodules are vendored",
        "read-only. Regenerate with `make frontmatter-report`; CI fails if this",
        "file drifts.",
        "",
        "Most runtimes trigger a skill from its YAML frontmatter, so a skill that",
        "omits `name`/`description` (or hides them behind a watermark banner) will",
        "silently fail to trigger. See `docs/skill-design-patterns.md` §7.",
        "",
        "## Schema",
        "",
        "| Field | Level | Meaning |",
        "|---|---|---|",
        "| `name` | **required** | how the runtime addresses the skill |",
        "| `description` | **required** | trigger text; how the runtime routes to it |",
        "| `license` | recommended | lets a single copied skill carry its own terms |",
        "| `version` | recommended | makes upgrades/drift legible |",
        "",
        "A skill *conforms* when it has real frontmatter with a non-empty `name`",
        "and `description`. Recommended fields are reported, never required.",
        "",
        "## At a glance",
        "",
        "| Metric | Count |",
        "|---|---:|",
        f"| `SKILL.md` files scanned | **{total:,}** |",
        f"| Conform to required schema | **{conforming:,}** ({pct(conforming, total)}%) |",
        f"| No YAML frontmatter at all | {no_fm:,} |",
        f"| Frontmatter but no `name` | {no_name:,} |",
        f"| Frontmatter but no `description` | {no_desc:,} |",
        f"| Declare a `license` (recommended) | {with_license:,} ({pct(with_license, total)}%) |",
        f"| Declare a `version` (recommended) | {with_version:,} ({pct(with_version, total)}%) |",
        "",
        "## Collections with non-conforming skills",
        "",
    ]
    if offenders:
        lines += [
            "Skills here miss a required field, so a strict loader will not",
            "auto-trigger them. Best fixed upstream.",
            "",
            "| Collection | Non-conforming | Of total |",
            "|---|---:|---:|",
        ]
        for name, count in offenders[:offender_rows]:
            lines.append(
                f"| `{md_escape(name)}` | {count} | {by_collection_total[name]} |"
            )
        if len(offenders) > offender_rows:
            remaining = sum(c for _, c in offenders[offender_rows:])
            lines.append(
                f"| _… and {len(offenders) - offender_rows} more collections_ "
                f"| {remaining} | |"
            )
    else:
        lines.append("Every scanned skill carries a conforming `name` + `description`. ✅")
    lines += [
        "",
        "---",
        "",
        "## Reproduce these numbers",
        "",
        "```bash",
        "python3 tools/check_frontmatter.py        # regenerate this file",
        "make frontmatter-report-check             # verify it is current",
        "```",
        "",
        "> Related: watermark banners that hide otherwise-valid frontmatter are",
        "> tallied in [`QUALITY.md`](QUALITY.md) §3; per-skill depth signals are",
        "> in [`MATURITY.md`](MATURITY.md).",
    ]
    return "\n".join(lines) + "\n"


def check_report(report: str) -> int:
    if not REPORT_PATH.exists():
        print("ERROR: missing catalog/FRONTMATTER.md")
        print("Run: python3 tools/check_frontmatter.py")
        return 1
    if REPORT_PATH.read_text(encoding="utf-8") != report:
        print("ERROR: catalog/FRONTMATTER.md is outdated")
        print("Run: python3 tools/check_frontmatter.py")
        return 1
    print("OK: catalog/FRONTMATTER.md is current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify catalog/FRONTMATTER.md is current without writing it",
    )
    args = parser.parse_args()

    skills_dir = ROOT / "skills"
    if not skills_dir.exists():
        print("skills/ not found; initialize submodules first.", file=sys.stderr)
        return 2

    load_submodule_urls()  # touch .gitmodules the same way the catalog does
    rows = scan()
    report = render_report(rows)

    if args.check:
        return check_report(report)

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"wrote {REPORT_PATH.relative_to(ROOT)} ({len(rows)} skills scanned)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
